engines:
  pmd:
    custom_rulesets:
      - force-app/main/default/Custom_apex_ruleset.xml
    file_extensions:
      - ".cls"
      - ".trigger"

  retire-js:
    disable_engine: false  # âœ… Enable retire-js, no extra config keys allowed

  eslint:
    disable_engine: true
  regex:
    disable_engine: true
  sfge:
    disable_engine: true
  flow:
    disable_engine: true
  cpd:
    disable_engine: true

rules:
  AvoidHardcodingId: {}
  ClassWithTooManyFields: {}
