engines:
  pmd:
    file_extensions:
      - ".cls"
      - ".trigger"
    config_file: force-app/main/default/Custom_apex_ruleset.xml
  retire-js:
    file_extensions:
      - ".js"
      - ".html"
    disable_engine: false

  eslint:
    disable_engine: true
  regex:
    disable_engine: true
  sfge:
    disable_engine: true
  flow:
    disable_engine: true
  cpd:
    disable_engine: true

rules:
  AvoidHardcodingId: {}
  ClassWithTooManyFields: {}
