targets:
  - "temp_scanner_files/"  # This will dynamically scan the folder with delta files
engines:
  - pmd
  - retire-js
formatters:
  - csv
normalize-severity: true
outfile: scanner-report-partial.csv
pmdconfig: force-app/main/default/Custom_apex_ruleset.xml
